name: apiverve_countrylanguages
description: Country Languages is a simple tool for getting the list of official and commonly spoken languages in a specific country.
version: 1.1.14
homepage: https://apiverve.com/marketplace/countrylanguages?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/countrylanguages-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
